feat: add --config cli argument
amperser/proselint pull request #1081
Opened 2020-06-10 21:29 UTC by reiddraper

This is useful for projects that want to provide their own proselintrc
which is stored in the repository for the project itself. Further, it's
useful for installations where putting a config-file outside of a
sandboxed directory is not possible.

---

Resolves #356. Resolves #1091.

2020-07-01 10:55 UTC, wargio commented
can we have this merged asap? i do not see why this wasn't already an option in the tool.

2021-05-23 10:38 UTC, carlsmedstad commented
Apart from needing a rebase on `main` and some clean up to pass the CI, this looks good to me.

Should @reiddraper continue this work? @Nytelife26 @suchow

2021-05-23 11:03 UTC, Nytelife26 commented
Thanks for bringing this to my attention, @carlsmedstad. I'll get to work on bringing it up to date and merging now, since it is a useful feature. We could also put automatically detecting proselintrc files up to the filesystem boundary as part of this PR, too, but that's another thing.

2021-05-23 11:09 UTC, carlsmedstad commented
Great, detecting project specific config files seems like something that would be useful after this has been merged.

I'm a proponent of the pattern of having three levels of configuration: system, user and project scope.

2021-05-23 14:06 UTC, Nytelife26 commented
> I'm a proponent of the pattern of having three levels of configuration:
> system, user and project scope.

Me too ultimately. The user configuration should check `~/.config` too, though.

2021-05-23 14:11 UTC, Nytelife26 approved these changes

2021-05-23 14:13 UTC, carlsmedstad commented
Definitely, I could make a PR tomorrow if you'd like?

2021-05-23 17:16 UTC, suchow commented
@Nytelife26 The CI run is failing here for one substantive reason (coverage) and one transition-to-Github-actions reason. In particular, something is breaking during the Danger action.

2021-05-24 00:26 UTC, Nytelife26 commented
> @Nytelife26 The CI run is failing here for one substantive reason
> (coverage) and one transition-to-Github-actions reason. In particular,
> something is breaking during the Danger action.

I am aware of the coverage issue. The test suite is not currently very
comprehensive, it seems.

As for the Danger action, I believe that is a result of the force push I
performed following the rebase, given that Danger specifies that as a
potential cause in the error log.

2021-05-24 09:32 UTC, Nytelife26 approved these changes

2021-05-24 17:57 UTC, Nytelife26 commented
cc: @suchow

2021-05-24 18:17 UTC, suchow requested changes

2021-05-24 18:17 UTC, suchow commented on tests/test_config_flag.py
> +"""Check that the --config command-line flag works"""
The test name and docstring suggest that this is testing the `--config` option, but the body is testing the `load_options` functions, which is one part of the pipeline that underlies the `--config` option handling. Did you test the end-to-end pipeline using the CLI tool? Minimally you could confirm you tested it manually. More fully, you could include a test of the `proselint()` function (setting the `config` kwarg) or even the `proselint` CLI command with the `--config` option set and not set.

2021-05-24 18:17 UTC, suchow commented on tests/test_config_flag.py
> +"""Check that the --config command-line flag works"""
Also, we're not using `--config` as a "flag" here, but as an "option".

2021-05-24 19:29 UTC, suchow reviewed
The new test looks good, just need to `import subprocess` up top and I think it should be good to go!

2021-05-24 22:43 UTC, merged

2021-05-25 13:44 UTC, benknoble commented
This doesn't resolve #1091, which is about individual checks versus categories.