chore: fix package metadata
amperser/proselint pull request #1183
Opened 2021-07-04 22:15 UTC by Nytelife26

## This relates to...

The package metadata and installation setup.

## Rationale

Prior to this, the package wheel would not build properly, and there
were erroneous setup files from the old package management system.

## Changes

- removed `setup.py` and `setup.cfg`
- added metadata to `pyproject.toml`
- added `.bumpversion.cfg`
- reformatted `README.md` and fixed some phrasing

### Features

### Bug Fixes

### Breaking Changes and Deprecations

2021-07-04 22:21 UTC, Nytelife26 commented
Unfortunately, we cannot fix the Danger issue until we merge this and cut a new release.

2021-07-04 23:07 UTC, suchow requested changes
Looks good, my only complaint is hard wrapping the Markdown, which isn’t necessary given that most editors can soft wrap Markdown text and keeping paragraphs on one line makes diffs more readable.

2021-07-05 12:26 UTC, Nytelife26 commented
> Looks good, my only complaint is hard wrapping the Markdown, which
> isn’t necessary given that most editors can soft wrap Markdown text
> and keeping paragraphs on one line makes diffs more readable.

That's something my editor does automatically, apologies - let me go fix
that quickly.

2021-07-05 14:58 UTC, suchow approved these changes

2021-07-05 16:31 UTC, merged